name: Shared API CI workflow

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  commitlint_remote:
    uses: nciocpl/nci.ocpl.api.shared/.github/workflows/api-ci.yml@shared-wf-test